# By submitting this assignment, I agree to the following:
#   "Aggies do not lie, cheat, or steal, or tolerate those who do."
#   "I have not given or received any unauthorized aid on this assignment."
#
# Name:         Maximus Amick
# Section:      513
# Assignment:   Lab: Topic 13 (individual)
# Date:         15 November 2025

import turtle as t

# // FUNCTIONS //

def parta(angle):
    """Draw the polygon generated by repeatedly turning 'angle' degrees until closing."""
    t.dot(10, "red")
    t.setheading(0)
    rotations = 0.0
    iterations = 0
    while True:
        t.forward(300)
        t.left(angle)
        iterations += 1
        rotations = (rotations + angle) % 360
        if abs(rotations) < 1e-6:
            break
    print(f"Smallest number of iterations needed for the turtle to return to its starting point: {iterations}")

def partb(sequence):
    """Trace the spirograph defined by the instruction string and report iterations."""
    t.dot(10, "red")
    start_position = t.position()
    for char in sequence:
        if char == "0":
            t.left(30)
        else:
            t.left(-114)
        t.forward(40)
    iterations = 1
    while t.distance(start_position) >= 1e-6:
        for char in sequence:
            if char == "0":
                t.left(30)
            else:
                t.left(-114)
            t.forward(40)
        iterations += 1
    print(f"Smallest number of iterations needed for the turtle to return to its starting point: {iterations}")

def partc(sequence, zero_angle, one_angle):
    """Draw a custom path reading 'sequence' and turning at 'zero_angle'/'one_angle'."""
    t.dot(10, "red")
    for char in sequence:
        if char == "0":
            t.left(zero_angle)
        else:
            t.left(one_angle)
        t.forward(5)

# // LE PROGRAMME //

def main():
    parta(160)
    
    input()
    t.reset()
    
    parta(141)
    
    input()
    t.reset()
    
    partb("01001")
    
    input()
    t.reset()
    
    partb("01001011")
    
    input()
    t.reset()
    
    seq1 = "".join("1" + "0"*k for k in range(20))
    partc(seq1, 0, 90)
    
    input()
    t.reset()
    
    partc(seq1, 0, 30)
    
    input()
    t.reset()
    
    seq2 = "".join("1" + "0"*k for k in range(50))
    partc(seq2, 0, 150)
    
    input()
    t.reset()
    
    partc(seq2, 5, 108)
    
    t.done()

# // MAIN GUARD //

if __name__ == "__main__":
    main()